name: CI Github - Update Automatic Memetics Motivation

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_index_automatic:
    runs-on: ubuntu-latest
    steps:
      - name: Step 0 - Checkout - put the repository files into the Github Actions runner
        uses: actions/checkout@v4

